(define
(problem test)
(:domain rubiks-cube)
(:objects yellow white blue green orange red)
(:init
    (cube1 orange yellow blue)
    (cube2 blue orange white)
    (cube3 green red white)
    (cube4 orange white green)
    (cube5 green yellow red)
    (cube6 orange green yellow)
    (cube7 white blue red)
    (cube8 blue red yellow)
    (edge12 yellow blue)
    (edge24 blue red)
    (edge34 white green)
    (edge13 orange white)
    (edge15 orange yellow)
    (edge26 green yellow)
    (edge48 red yellow)
    (edge37 orange blue)
    (edge56 red white)
    (edge68 green red)
    (edge78 white blue)
    (edge57 green orange)
)
(:goal
    (and
        (cube1 red white blue)
        (cube2 orange white blue)
        (cube3 red yellow blue)
        (cube4 orange yellow blue)
        (cube5 red white green)
        (cube6 orange white green)
        (cube7 red yellow green)
        (cube8 orange yellow green)

        (edge12 white blue)
        (edge24 orange blue)
        (edge34 yellow blue)
        (edge13 red blue)

        (edge15 red white)
        (edge26 orange white)
        (edge48 orange yellow)
        (edge37 red yellow)

        (edge56 white green)
        (edge68 orange green)
        (edge78 yellow green)
        (edge57 red green)

    )
)
)