(define
(problem test)
(:domain rubiks-cube)
(:objects yellow white blue green orange red)
(:init
    (cube1 red blue yellow)
    (cube2 red white green)
    (cube3 orange green white)
    (cube4 blue orange yellow)
    (cube5 red blue white)
    (cube6 orange blue white)
    (cube7 green red yellow)
    (cube8 yellow green orange)
    (edge12 white green)
    (edge24 white blue)
    (edge34 yellow red)
    (edge13 orange white)
    (edge15 red blue)
    (edge26 red white)
    (edge48 blue orange)
    (edge37 yellow blue)
    (edge56 orange green)
    (edge68 yellow orange)
    (edge78 red green)
    (edge57 green yellow)
)
(:goal
    (and
        (cube1 red white blue)
        (cube2 orange white blue)
        (cube3 red yellow blue)
        (cube4 orange yellow blue)
        (cube5 red white green)
        (cube6 orange white green)
        (cube7 red yellow green)
        (cube8 orange yellow green)

        (edge12 white blue)
        (edge24 orange blue)
        (edge34 yellow blue)
        (edge13 red blue)

        (edge15 red white)
        (edge26 orange white)
        (edge48 orange yellow)
        (edge37 red yellow)

        (edge56 white green)
        (edge68 orange green)
        (edge78 yellow green)
        (edge57 red green)

    )
)
)